name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failures }}
    strategy:
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3']
        allow-failures: [false]
        include:
          - ruby: head
            allow-failures: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          # Until https://github.com/ONLYOFFICE-QA/wrata_api/issues/342 is resolved
          # bundle exec rake
