name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set latest stable ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Setup ruby dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Check source files using `rubocop`
        run: rubocop
      - name: Check that code 100% documented
        run: yardoc . | grep -q '100.00% documented'
